### ISSUE TITLE
[feature]: 升级 ZkClient 客户端，转为使用 Curator 客户端

### ISSUE THREAD

**Issue by BanTanger** [BanTanger/im-whale-shark#60]
目前使用官方 ZkClient，代码比较丑陋

https://github.com/BanTanger/im-whale-shark/blob/433e1f24e5ad4d989978bbd823d6374c75bd0287/im-infrastructure/src/main/java/com/bantanger/im/service/zookeeper/ZkManager.java#L27-L44

而 Curator 方式创建节点的一个例子如下：
```java
CuratorFramework client = CuratorFrameworkFactory.newClient(connectionAddr,  retryPolicy);
String zkPath = "/test/node-1";
client.create().withMode(mode).forPath(zkPath);
```

使用 Curator 的好处：
1. 官方 ZkClient 社区不活跃，文档不完善，仅仅是因为他是 ZK 官方客户端而有大量的人使用
2. 官方 ZkClient 异常处理简单，仅仅为抛出 RuntimeException，相比之下 Curator 抛出更为精确的 NodeExistsException 等等
3. 官方 ZkClient 重试机制难用，而 Curator 支持 Session 会话超时重连，掉线重连，反复注册 Watcher
4. 官方 ZkClient 没有提供各种使用场景的例子，基本都只能参考互联网上的文章，缺乏公信力，且遇到问题难以从官方文档着手定位
5. Curator 提供 Zk 比较常用的 分布式开发轮子，如 Recipes、共享锁，Master 节点选举，分布式计算器等等。且具有链式 API

**Comment by BanTanger** [comment]
如果 Curator 与 ZooKeeper 的版本不是相互匹配的，就会有兼容性问题，很有可能导 致节点操作失败。确保Curator与ZooKeeper的具体的版本可以去 curator 的官网查看配套关系。

**Comment by BanTanger** [comment]
> 如果 Curator 与 ZooKeeper 的版本不是相互匹配的，就会有兼容性问题，很有可能导 致节点操作失败。确保Curator与ZooKeeper的具体的版本可以去 curator 的官网查看配套关系。

目前 Curator 版本 2.12.0 <==> Zookeeper 版本 3.4.13

**Comment by BanTanger** [comment]
zk 3.5.10 docker 报错
2023-12-14 17:25:21 java.lang.NullPointerException
2023-12-14 17:25:21     at org.apache.zookeeper.server.ContainerManager.getCandidates(ContainerManager.java:143)
2023-12-14 17:25:21     at org.apache.zookeeper.server.ContainerManager.checkContainers(ContainerManager.java:112)
2023-12-14 17:25:21     at org.apache.zookeeper.server.ContainerManager$1.run(ContainerManager.java:78)
2023-12-14 17:25:21     at java.base/java.util.TimerThread.mainLoop(Unknown Source)
2023-12-14 17:25:21     at java.base/java.util.TimerThread.run(Unknown Source)
2023-12-14 17:26:21 2023-12-14 09:26:21,106 [myid:1] - ERROR [ContainerManagerTask:ContainerManager$1@84] - Error checking containers

使用 curator 连接报错：
[2023-12-14 17:45:18.536 +0800] [] [main-SendThread(127.0.0.1:2181)] [INFO] [org.apache.zookeeper.ClientCnxn] [Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)]
[2023-12-14 17:45:18.538 +0800] [] [main-SendThread(127.0.0.1:2181)] [INFO] [org.apache.zookeeper.ClientCnxn] [Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session]
[2023-12-14 17:45:18.539 +0800] [] [main-SendThread(127.0.0.1:2181)] [INFO] [org.apache.zookeeper.ClientCnxn] [Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect]

创建节点错误
KeeperErrorCode = ConnectionLoss for /im-coreRoot/web/192.168.3.31:19002

进 docker 容器 执行 `zkServer.sh status` 情况如下：
```shell
ZooKeeper JMX enabled by default 
Using config: /conf/zoo.cfg 
Client port not found in static config file. 
Looking in dynamic config file. 
grep: : No such file or directory 
Client port not found in the server configs 
Client port not found. 
Looking for secureClientPort in the static config. 
Unable to find either secure or unsecure client port in any configs. 
Terminating
```

而其他版本执行如下：
```shell
zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
Mode: standalone
```
